### ISSUE TITLE
Because why would anything be easy

### ISSUE THREAD

**Issue by Zed-Leppin** [BadByteGames/Glass-Wall#2]
Ahem:
streambuff
Base class 'std::__1::ios_base' has private copy constructor
istream
No matching constructor for initialization of 'basic_ios<char, std::__1::char_traits<char> >'
FileManager.cpp
No mathing constructor for initilization of 'std::ifstream' (aka 'basic_ifstream<char>')

And a bunch of deprecated stuff which I guess isn't bad

**Comment by armedturret** [comment]
Can you look around to get the line where this is occurring at by clicking the error? TherE is two functions in fIle manager.

**Comment by armedturret** [comment]
Once again I did a goof. Ifstreams can't be copied. Will fix in next update.
